services:
  - type: pserv
    name: my-postgres-db
    env: docker
    plan: free
    autoDeploy: true
    ports:
      - port: 5432
    envVars:
      - key: POSTGRES_PASSWORD
        value: $Tic@n@350*