services:
  - type: web
    name: postgres-n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: POSTGRES_PASSWORD
        value: "$Tic@n@350*"
      - key: POSTGRES_USER
        value: Fredb1380_db
      - key: POSTGRES_DB
        value: db_n8n_render_postgres
    ports:
      - port: 5432
        protocol: tcp
      - port: 80
        protocol: http